### ISSUE TITLE
Fails due to missing github fields

### ISSUE THREAD

**Issue by orhun** [adamperkowski/nvrs#2]
Hey! 👋🏼 

I'm getting the following error while running `nvrs` with this [config file](https://github.com/orhun/PKGBUILDs/blob/master/nvchecker.toml):

```
 nvrs --config nvchecker.toml
thread 'main' panicked at src/config.rs:40:42:
failed to read the config file: Error { inner: Error { inner: TomlError { message: "missing field `github`",
```

It is probably due to the other source in that file (e.g. `gitlab`). Can we make `github` field optional and skip the other sources if possible?

Awesome stuff, thanks!

**Comment by adamperkowski** [comment]
Yeah I know about this. 

> Can we make github field optional and skip the other sources if possible?

I'll refactor that part of the code when I'll be adding more sources. 

Thanks.
