### ISSUE TITLE
panic when trying to deserialize a verfile that has fields missing

### ISSUE THREAD

**Issue by orhun** [adamperkowski/nvrs#3]
I don't know what's going on, but I'm hitting another error with [my config](https://github.com/orhun/PKGBUILDs/blob/master/nvchecker.toml):

```
thread 'main' panicked at src/verfiles.rs:88:36:
failed to read oldver: Error("missing field `gitref`", line: 1591, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by adamperkowski** [comment]
Interesting. Will definitely check it out. Are you using the latest version?

**Comment by adamperkowski** [comment]
Actually, I'll just allow missing fields and taking unupdated versions.

**Comment by orhun** [comment]
Sounds great, thanks for fixing it! Can we get a new release? 😊

**Comment by adamperkowski** [comment]
> Sounds great, thanks for fixing it! Can we get a new release? 😊

I might do one more improvement.
